name: Build FidoIP

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Build packages
        run: ./create_packages.bash

      - name: upload binaries to release
        uses: softprops/action-gh-release@v2
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
          files: |
            packages/binkd-1.1a-115-x86_64-Linux-fido_my1.tgz
            packages/golded-1.1.5-b-x86_64-Linux-fido_my1.tgz
            packages/husky-1.9-x86_64-Linux-fido_my1.tgz
